// Code generated by tinyjson for marshaling/unmarshaling. DO NOT EDIT.

package mapping

import (
	tinyjson "github.com/CosmWasm/tinyjson"
	jlexer "github.com/CosmWasm/tinyjson/jlexer"
	jwriter "github.com/CosmWasm/tinyjson/jwriter"
)

// suppress unused package warning
var (
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ tinyjson.Marshaler
)

func tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping(in *jlexer.Lexer, out *VerificationRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "block_height":
			out.BlockHeight = uint32(in.Uint32())
		case "raw_tx_hex":
			out.RawTxHex = string(in.String())
		case "merkle_proof_hex":
			out.MerkleProofHex = string(in.String())
		case "tx_index":
			out.TxIndex = uint32(in.Uint32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping(out *jwriter.Writer, in VerificationRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"block_height\":"
		out.RawString(prefix[1:])
		out.Uint32(uint32(in.BlockHeight))
	}
	{
		const prefix string = ",\"raw_tx_hex\":"
		out.RawString(prefix)
		out.String(string(in.RawTxHex))
	}
	{
		const prefix string = ",\"merkle_proof_hex\":"
		out.RawString(prefix)
		out.String(string(in.MerkleProofHex))
	}
	{
		const prefix string = ",\"tx_index\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.TxIndex))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v VerificationRequest) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *VerificationRequest) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping(l, v)
}
func tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping1(in *jlexer.Lexer, out *UtxoMap) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
	} else {
		in.Delim('{')
		*out = make(UtxoMap)
		for !in.IsDelim('}') {
			key := string(in.String())
			in.WantColon()
			var v1 *Utxo
			if in.IsNull() {
				in.Skip()
				v1 = nil
			} else {
				if v1 == nil {
					v1 = new(Utxo)
				}
				(*v1).UnmarshalTinyJSON(in)
			}
			(*out)[key] = v1
			in.WantComma()
		}
		in.Delim('}')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping1(out *jwriter.Writer, in UtxoMap) {
	if in == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
		out.RawString(`null`)
	} else {
		out.RawByte('{')
		v2First := true
		for v2Name, v2Value := range in {
			if v2First {
				v2First = false
			} else {
				out.RawByte(',')
			}
			out.String(string(v2Name))
			out.RawByte(':')
			if v2Value == nil {
				out.RawString("null")
			} else {
				(*v2Value).MarshalTinyJSON(out)
			}
		}
		out.RawByte('}')
	}
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v UtxoMap) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping1(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *UtxoMap) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping1(l, v)
}
func tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping2(in *jlexer.Lexer, out *Utxo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "tx_id":
			out.TxId = string(in.String())
		case "vout":
			out.Vout = uint32(in.Uint32())
		case "amount":
			out.Amount = int64(in.Int64())
		case "pk_script":
			if in.IsNull() {
				in.Skip()
				out.PkScript = nil
			} else {
				out.PkScript = in.Bytes()
			}
		case "tag":
			out.Tag = string(in.String())
		case "confirmed":
			out.Confirmed = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping2(out *jwriter.Writer, in Utxo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"tx_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.TxId))
	}
	{
		const prefix string = ",\"vout\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.Vout))
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.Int64(int64(in.Amount))
	}
	{
		const prefix string = ",\"pk_script\":"
		out.RawString(prefix)
		out.Base64Bytes(in.PkScript)
	}
	{
		const prefix string = ",\"tag\":"
		out.RawString(prefix)
		out.String(string(in.Tag))
	}
	{
		const prefix string = ",\"confirmed\":"
		out.RawString(prefix)
		out.Bool(bool(in.Confirmed))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v Utxo) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping2(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *Utxo) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping2(l, v)
}
func tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping3(in *jlexer.Lexer, out *UnmappingInputData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "amount":
			out.Amount = int64(in.Int64())
		case "recipient_btc_address":
			out.RecipientBtcAddress = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping3(out *jwriter.Writer, in UnmappingInputData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Amount))
	}
	{
		const prefix string = ",\"recipient_btc_address\":"
		out.RawString(prefix)
		out.String(string(in.RecipientBtcAddress))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v UnmappingInputData) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping3(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *UnmappingInputData) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping3(l, v)
}
func tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping4(in *jlexer.Lexer, out *TxSpends) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
	} else {
		in.Delim('{')
		*out = make(TxSpends)
		for !in.IsDelim('}') {
			key := string(in.String())
			in.WantColon()
			var v6 *SigningData
			if in.IsNull() {
				in.Skip()
				v6 = nil
			} else {
				if v6 == nil {
					v6 = new(SigningData)
				}
				tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping5(in, v6)
			}
			(*out)[key] = v6
			in.WantComma()
		}
		in.Delim('}')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping4(out *jwriter.Writer, in TxSpends) {
	if in == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
		out.RawString(`null`)
	} else {
		out.RawByte('{')
		v7First := true
		for v7Name, v7Value := range in {
			if v7First {
				v7First = false
			} else {
				out.RawByte(',')
			}
			out.String(string(v7Name))
			out.RawByte(':')
			if v7Value == nil {
				out.RawString("null")
			} else {
				tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping5(out, *v7Value)
			}
		}
		out.RawByte('}')
	}
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v TxSpends) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping4(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *TxSpends) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping4(l, v)
}
func tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping5(in *jlexer.Lexer, out *SigningData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "tx":
			out.Tx = string(in.String())
		case "unsigned_sig_hashes":
			if in.IsNull() {
				in.Skip()
				out.UnsignedSigHashes = nil
			} else {
				in.Delim('[')
				if out.UnsignedSigHashes == nil {
					if !in.IsDelim(']') {
						out.UnsignedSigHashes = make([]UnsignedSigHash, 0, 1)
					} else {
						out.UnsignedSigHashes = []UnsignedSigHash{}
					}
				} else {
					out.UnsignedSigHashes = (out.UnsignedSigHashes)[:0]
				}
				for !in.IsDelim(']') {
					var v8 UnsignedSigHash
					tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping6(in, &v8)
					out.UnsignedSigHashes = append(out.UnsignedSigHashes, v8)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping5(out *jwriter.Writer, in SigningData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"tx\":"
		out.RawString(prefix[1:])
		out.String(string(in.Tx))
	}
	{
		const prefix string = ",\"unsigned_sig_hashes\":"
		out.RawString(prefix)
		if in.UnsignedSigHashes == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v9, v10 := range in.UnsignedSigHashes {
				if v9 > 0 {
					out.RawByte(',')
				}
				tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping6(out, v10)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}
func tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping6(in *jlexer.Lexer, out *UnsignedSigHash) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "index":
			out.Index = uint32(in.Uint32())
		case "sig_hash":
			out.SigHash = string(in.String())
		case "witness_script":
			out.WitnessScript = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping6(out *jwriter.Writer, in UnsignedSigHash) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"index\":"
		out.RawString(prefix[1:])
		out.Uint32(uint32(in.Index))
	}
	{
		const prefix string = ",\"sig_hash\":"
		out.RawString(prefix)
		out.String(string(in.SigHash))
	}
	{
		const prefix string = ",\"witness_script\":"
		out.RawString(prefix)
		out.String(string(in.WitnessScript))
	}
	out.RawByte('}')
}
func tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping7(in *jlexer.Lexer, out *TransferInputData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "amount":
			out.Amount = int64(in.Int64())
		case "recipient_vsc_address":
			out.RecipientVscAddress = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping7(out *jwriter.Writer, in TransferInputData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Amount))
	}
	{
		const prefix string = ",\"recipient_vsc_address\":"
		out.RawString(prefix)
		out.String(string(in.RecipientVscAddress))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v TransferInputData) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping7(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *TransferInputData) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping7(l, v)
}
func tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping8(in *jlexer.Lexer, out *SystemSupply) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "active_supply":
			out.ActiveSupply = int64(in.Int64())
		case "user_supply":
			out.UserSupply = int64(in.Int64())
		case "fee_supply":
			out.FeeSupply = int64(in.Int64())
		case "base_fee_rate":
			out.BaseFeeRate = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping8(out *jwriter.Writer, in SystemSupply) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"active_supply\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ActiveSupply))
	}
	{
		const prefix string = ",\"user_supply\":"
		out.RawString(prefix)
		out.Int64(int64(in.UserSupply))
	}
	{
		const prefix string = ",\"fee_supply\":"
		out.RawString(prefix)
		out.Int64(int64(in.FeeSupply))
	}
	{
		const prefix string = ",\"base_fee_rate\":"
		out.RawString(prefix)
		out.Int64(int64(in.BaseFeeRate))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v SystemSupply) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping8(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *SystemSupply) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping8(l, v)
}
func tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping9(in *jlexer.Lexer, out *ObservedTxList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
	} else {
		in.Delim('{')
		*out = make(ObservedTxList)
		for !in.IsDelim('}') {
			key := string(in.String())
			in.WantColon()
			var v11 bool
			v11 = bool(in.Bool())
			(*out)[key] = v11
			in.WantComma()
		}
		in.Delim('}')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping9(out *jwriter.Writer, in ObservedTxList) {
	if in == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
		out.RawString(`null`)
	} else {
		out.RawByte('{')
		v12First := true
		for v12Name, v12Value := range in {
			if v12First {
				v12First = false
			} else {
				out.RawByte(',')
			}
			out.String(string(v12Name))
			out.RawByte(':')
			out.Bool(bool(v12Value))
		}
		out.RawByte('}')
	}
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v ObservedTxList) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping9(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *ObservedTxList) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping9(l, v)
}
func tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping10(in *jlexer.Lexer, out *MappingInputData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "tx_data":
			if in.IsNull() {
				in.Skip()
				out.TxData = nil
			} else {
				if out.TxData == nil {
					out.TxData = new(VerificationRequest)
				}
				(*out.TxData).UnmarshalTinyJSON(in)
			}
		case "instructions":
			if in.IsNull() {
				in.Skip()
				out.Instructions = nil
			} else {
				in.Delim('[')
				if out.Instructions == nil {
					if !in.IsDelim(']') {
						out.Instructions = make([]string, 0, 4)
					} else {
						out.Instructions = []string{}
					}
				} else {
					out.Instructions = (out.Instructions)[:0]
				}
				for !in.IsDelim(']') {
					var v13 string
					v13 = string(in.String())
					out.Instructions = append(out.Instructions, v13)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping10(out *jwriter.Writer, in MappingInputData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"tx_data\":"
		out.RawString(prefix[1:])
		if in.TxData == nil {
			out.RawString("null")
		} else {
			(*in.TxData).MarshalTinyJSON(out)
		}
	}
	{
		const prefix string = ",\"instructions\":"
		out.RawString(prefix)
		if in.Instructions == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v14, v15 := range in.Instructions {
				if v14 > 0 {
					out.RawByte(',')
				}
				out.String(string(v15))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v MappingInputData) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping10(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *MappingInputData) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping10(l, v)
}
func tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping11(in *jlexer.Lexer, out *HeaderMap) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
	} else {
		in.Delim('{')
		*out = make(HeaderMap)
		for !in.IsDelim('}') {
			key := uint32(in.Uint32Str())
			in.WantColon()
			var v16 []uint8
			if in.IsNull() {
				in.Skip()
				v16 = nil
			} else {
				v16 = in.Bytes()
			}
			(*out)[key] = v16
			in.WantComma()
		}
		in.Delim('}')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping11(out *jwriter.Writer, in HeaderMap) {
	if in == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
		out.RawString(`null`)
	} else {
		out.RawByte('{')
		v18First := true
		for v18Name, v18Value := range in {
			if v18First {
				v18First = false
			} else {
				out.RawByte(',')
			}
			out.Uint32Str(uint32(v18Name))
			out.RawByte(':')
			out.Base64Bytes(v18Value)
		}
		out.RawByte('}')
	}
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v HeaderMap) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping11(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *HeaderMap) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping11(l, v)
}
func tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping12(in *jlexer.Lexer, out *AccountInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "modified_at":
			out.ModifiedAt = uint64(in.Uint64())
		case "address":
			out.Address = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping12(out *jwriter.Writer, in AccountInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"modified_at\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.ModifiedAt))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v AccountInfo) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping12(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *AccountInfo) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping12(l, v)
}
func tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping13(in *jlexer.Lexer, out *AccountBalanceMap) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
	} else {
		in.Delim('{')
		*out = make(AccountBalanceMap)
		for !in.IsDelim('}') {
			key := string(in.String())
			in.WantColon()
			var v21 int64
			v21 = int64(in.Int64())
			(*out)[key] = v21
			in.WantComma()
		}
		in.Delim('}')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping13(out *jwriter.Writer, in AccountBalanceMap) {
	if in == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
		out.RawString(`null`)
	} else {
		out.RawByte('{')
		v22First := true
		for v22Name, v22Value := range in {
			if v22First {
				v22First = false
			} else {
				out.RawByte(',')
			}
			out.String(string(v22Name))
			out.RawByte(':')
			out.Int64(int64(v22Value))
		}
		out.RawByte('}')
	}
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v AccountBalanceMap) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeExampleComBuildingTinyjsonMapping13(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *AccountBalanceMap) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeExampleComBuildingTinyjsonMapping13(l, v)
}
