// Code generated by tinyjson for marshaling/unmarshaling. DO NOT EDIT.

package blocklist

import (
	tinyjson "github.com/CosmWasm/tinyjson"
	jlexer "github.com/CosmWasm/tinyjson/jlexer"
	jwriter "github.com/CosmWasm/tinyjson/jwriter"
)

// suppress unused package warning
var (
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ tinyjson.Marshaler
)

func tinyjson2d7d9c89DecodeBtcMappingContractContractBlocklistTinyjsonTmp(in *jlexer.Lexer, out *BlockSeedInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "block_header":
			out.BlockHeader = string(in.String())
		case "block_height":
			out.BlockHeight = uint32(in.Uint32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson2d7d9c89EncodeBtcMappingContractContractBlocklistTinyjsonTmp(out *jwriter.Writer, in BlockSeedInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"block_header\":"
		out.RawString(prefix[1:])
		out.String(string(in.BlockHeader))
	}
	{
		const prefix string = ",\"block_height\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.BlockHeight))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v BlockSeedInput) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson2d7d9c89EncodeBtcMappingContractContractBlocklistTinyjsonTmp(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *BlockSeedInput) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson2d7d9c89DecodeBtcMappingContractContractBlocklistTinyjsonTmp(l, v)
}
func tinyjson2d7d9c89DecodeBtcMappingContractContractBlocklistTinyjsonTmp1(in *jlexer.Lexer, out *AddBlocksInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "blocks":
			out.Blocks = string(in.String())
		case "latest_fee":
			out.LatestFee = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson2d7d9c89EncodeBtcMappingContractContractBlocklistTinyjsonTmp1(out *jwriter.Writer, in AddBlocksInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"blocks\":"
		out.RawString(prefix[1:])
		out.String(string(in.Blocks))
	}
	{
		const prefix string = ",\"latest_fee\":"
		out.RawString(prefix)
		out.Int64(int64(in.LatestFee))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v AddBlocksInput) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson2d7d9c89EncodeBtcMappingContractContractBlocklistTinyjsonTmp1(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *AddBlocksInput) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson2d7d9c89DecodeBtcMappingContractContractBlocklistTinyjsonTmp1(l, v)
}
