// Code generated by tinyjson for marshaling/unmarshaling. DO NOT EDIT.

package mapping

import (
	tinyjson "github.com/CosmWasm/tinyjson"
	jlexer "github.com/CosmWasm/tinyjson/jlexer"
	jwriter "github.com/CosmWasm/tinyjson/jwriter"
)

// suppress unused package warning
var (
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ tinyjson.Marshaler
)

func tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp(in *jlexer.Lexer, out *VerificationRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "block_height":
			out.BlockHeight = uint32(in.Uint32())
		case "raw_tx_hex":
			out.RawTxHex = string(in.String())
		case "merkle_proof_hex":
			out.MerkleProofHex = string(in.String())
		case "tx_index":
			out.TxIndex = uint32(in.Uint32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp(out *jwriter.Writer, in VerificationRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"block_height\":"
		out.RawString(prefix[1:])
		out.Uint32(uint32(in.BlockHeight))
	}
	{
		const prefix string = ",\"raw_tx_hex\":"
		out.RawString(prefix)
		out.String(string(in.RawTxHex))
	}
	{
		const prefix string = ",\"merkle_proof_hex\":"
		out.RawString(prefix)
		out.String(string(in.MerkleProofHex))
	}
	{
		const prefix string = ",\"tx_index\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.TxIndex))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v VerificationRequest) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *VerificationRequest) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp(l, v)
}
func tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp1(in *jlexer.Lexer, out *ValidatorAttestation) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "validator_did":
			out.ValidatorDID = string(in.String())
		case "pubkey_hex":
			out.PubkeyHex = string(in.String())
		case "sig_hex":
			out.BlsSigHex = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp1(out *jwriter.Writer, in ValidatorAttestation) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"validator_did\":"
		out.RawString(prefix[1:])
		out.String(string(in.ValidatorDID))
	}
	{
		const prefix string = ",\"pubkey_hex\":"
		out.RawString(prefix)
		out.String(string(in.PubkeyHex))
	}
	{
		const prefix string = ",\"sig_hex\":"
		out.RawString(prefix)
		out.String(string(in.BlsSigHex))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v ValidatorAttestation) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp1(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *ValidatorAttestation) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp1(l, v)
}
func tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp2(in *jlexer.Lexer, out *TransferParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "amount":
			out.Amount = string(in.String())
		case "to":
			out.To = string(in.String())
		case "from":
			out.From = string(in.String())
		case "deduct_fee":
			out.DeductFee = bool(in.Bool())
		case "max_fee":
			if in.IsNull() {
				in.Skip()
				out.MaxFee = nil
			} else {
				if out.MaxFee == nil {
					out.MaxFee = new(int64)
				}
				*out.MaxFee = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp2(out *jwriter.Writer, in TransferParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix[1:])
		out.String(string(in.Amount))
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		out.String(string(in.To))
	}
	if in.From != "" {
		const prefix string = ",\"from\":"
		out.RawString(prefix)
		out.String(string(in.From))
	}
	if in.DeductFee {
		const prefix string = ",\"deduct_fee\":"
		out.RawString(prefix)
		out.Bool(bool(in.DeductFee))
	}
	if in.MaxFee != nil {
		const prefix string = ",\"max_fee\":"
		out.RawString(prefix)
		out.Int64(int64(*in.MaxFee))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v TransferParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp2(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *TransferParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp2(l, v)
}
func tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp3(in *jlexer.Lexer, out *SwapResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "amount_out":
			out.AmountOut = string(in.String())
		case "pool_state":
			(out.PoolState).UnmarshalTinyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp3(out *jwriter.Writer, in SwapResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"amount_out\":"
		out.RawString(prefix[1:])
		out.String(string(in.AmountOut))
	}
	{
		const prefix string = ",\"pool_state\":"
		out.RawString(prefix)
		(in.PoolState).MarshalTinyJSON(out)
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v SwapResult) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp3(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *SwapResult) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp3(l, v)
}
func tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp4(in *jlexer.Lexer, out *RouterContract) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "router_contract":
			out.ContractId = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp4(out *jwriter.Writer, in RouterContract) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"router_contract\":"
		out.RawString(prefix[1:])
		out.String(string(in.ContractId))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v RouterContract) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp4(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *RouterContract) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp4(l, v)
}
func tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp5(in *jlexer.Lexer, out *RegisterKeyParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "primary_public_key":
			out.PrimaryPubKey = string(in.String())
		case "backup_public_key":
			out.BackupPubKey = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp5(out *jwriter.Writer, in RegisterKeyParams) {
	out.RawByte('{')
	first := true
	_ = first
	if in.PrimaryPubKey != "" {
		const prefix string = ",\"primary_public_key\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.PrimaryPubKey))
	}
	if in.BackupPubKey != "" {
		const prefix string = ",\"backup_public_key\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.BackupPubKey))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v RegisterKeyParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp5(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *RegisterKeyParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp5(l, v)
}
func tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp6(in *jlexer.Lexer, out *PoolInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "asset0":
			out.Asset0 = string(in.String())
		case "asset1":
			out.Asset1 = string(in.String())
		case "reserve0":
			out.Reserve0 = string(in.String())
		case "reserve1":
			out.Reserve1 = string(in.String())
		case "fee":
			out.Fee = uint64(in.Uint64())
		case "total_lp":
			out.TotalLp = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp6(out *jwriter.Writer, in PoolInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"asset0\":"
		out.RawString(prefix[1:])
		out.String(string(in.Asset0))
	}
	{
		const prefix string = ",\"asset1\":"
		out.RawString(prefix)
		out.String(string(in.Asset1))
	}
	{
		const prefix string = ",\"reserve0\":"
		out.RawString(prefix)
		out.String(string(in.Reserve0))
	}
	{
		const prefix string = ",\"reserve1\":"
		out.RawString(prefix)
		out.String(string(in.Reserve1))
	}
	{
		const prefix string = ",\"fee\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Fee))
	}
	{
		const prefix string = ",\"total_lp\":"
		out.RawString(prefix)
		out.String(string(in.TotalLp))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v PoolInfo) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp6(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *PoolInfo) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp6(l, v)
}
func tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp7(in *jlexer.Lexer, out *MapParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "tx_data":
			if in.IsNull() {
				in.Skip()
				out.TxData = nil
			} else {
				if out.TxData == nil {
					out.TxData = new(VerificationRequest)
				}
				(*out.TxData).UnmarshalTinyJSON(in)
			}
		case "instructions":
			if in.IsNull() {
				in.Skip()
				out.Instructions = nil
			} else {
				in.Delim('[')
				if out.Instructions == nil {
					if !in.IsDelim(']') {
						out.Instructions = make([]string, 0, 4)
					} else {
						out.Instructions = []string{}
					}
				} else {
					out.Instructions = (out.Instructions)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.Instructions = append(out.Instructions, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp7(out *jwriter.Writer, in MapParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"tx_data\":"
		out.RawString(prefix[1:])
		if in.TxData == nil {
			out.RawString("null")
		} else {
			(*in.TxData).MarshalTinyJSON(out)
		}
	}
	{
		const prefix string = ",\"instructions\":"
		out.RawString(prefix)
		if in.Instructions == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Instructions {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v MapParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp7(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *MapParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp7(l, v)
}
func tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp8(in *jlexer.Lexer, out *MapInstantSendV2ParamsFull) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "body":
			(out.Body).UnmarshalTinyJSON(in)
		case "agg":
			(out.Agg).UnmarshalTinyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp8(out *jwriter.Writer, in MapInstantSendV2ParamsFull) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"body\":"
		out.RawString(prefix[1:])
		(in.Body).MarshalTinyJSON(out)
	}
	{
		const prefix string = ",\"agg\":"
		out.RawString(prefix)
		(in.Agg).MarshalTinyJSON(out)
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v MapInstantSendV2ParamsFull) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp8(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *MapInstantSendV2ParamsFull) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp8(l, v)
}
func tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp9(in *jlexer.Lexer, out *MapInstantSendV2Params) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "raw_tx_hex":
			out.RawTxHex = string(in.String())
		case "instruction":
			out.Instruction = string(in.String())
		case "epoch":
			out.Epoch = uint64(in.Uint64())
		case "attestations":
			if in.IsNull() {
				in.Skip()
				out.Attestations = nil
			} else {
				in.Delim('[')
				if out.Attestations == nil {
					if !in.IsDelim(']') {
						out.Attestations = make([]ValidatorAttestation, 0, 1)
					} else {
						out.Attestations = []ValidatorAttestation{}
					}
				} else {
					out.Attestations = (out.Attestations)[:0]
				}
				for !in.IsDelim(']') {
					var v4 ValidatorAttestation
					(v4).UnmarshalTinyJSON(in)
					out.Attestations = append(out.Attestations, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "chain_id":
			out.ChainId = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp9(out *jwriter.Writer, in MapInstantSendV2Params) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"raw_tx_hex\":"
		out.RawString(prefix[1:])
		out.String(string(in.RawTxHex))
	}
	{
		const prefix string = ",\"instruction\":"
		out.RawString(prefix)
		out.String(string(in.Instruction))
	}
	{
		const prefix string = ",\"epoch\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Epoch))
	}
	{
		const prefix string = ",\"attestations\":"
		out.RawString(prefix)
		if in.Attestations == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Attestations {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalTinyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"chain_id\":"
		out.RawString(prefix)
		out.String(string(in.ChainId))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v MapInstantSendV2Params) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp9(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *MapInstantSendV2Params) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp9(l, v)
}
func tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp10(in *jlexer.Lexer, out *DexInstruction) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "type":
			out.Type = string(in.String())
		case "version":
			out.Version = string(in.String())
		case "asset_in":
			out.AssetIn = string(in.String())
		case "asset_out":
			out.AssetOut = string(in.String())
		case "recipient":
			out.Recipient = string(in.String())
		case "min_amount_out":
			if in.IsNull() {
				in.Skip()
				out.MinAmountOut = nil
			} else {
				if out.MinAmountOut == nil {
					out.MinAmountOut = new(string)
				}
				*out.MinAmountOut = string(in.String())
			}
		case "beneficiary":
			if in.IsNull() {
				in.Skip()
				out.Beneficiary = nil
			} else {
				if out.Beneficiary == nil {
					out.Beneficiary = new(string)
				}
				*out.Beneficiary = string(in.String())
			}
		case "ref_bps":
			if in.IsNull() {
				in.Skip()
				out.RefBps = nil
			} else {
				if out.RefBps == nil {
					out.RefBps = new(uint64)
				}
				*out.RefBps = uint64(in.Uint64())
			}
		case "return_address":
			if in.IsNull() {
				in.Skip()
				out.ReturnAddress = nil
			} else {
				if out.ReturnAddress == nil {
					out.ReturnAddress = new(ReturnAddress)
				}
				tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp11(in, out.ReturnAddress)
			}
		case "metadata":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Metadata = make(map[string]string)
				} else {
					out.Metadata = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v7 string
					v7 = string(in.String())
					(out.Metadata)[key] = v7
					in.WantComma()
				}
				in.Delim('}')
			}
		case "amount_in":
			out.AmountIn = string(in.String())
		case "destination_chain":
			out.DestinationChain = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp10(out *jwriter.Writer, in DexInstruction) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.String(string(in.Version))
	}
	{
		const prefix string = ",\"asset_in\":"
		out.RawString(prefix)
		out.String(string(in.AssetIn))
	}
	{
		const prefix string = ",\"asset_out\":"
		out.RawString(prefix)
		out.String(string(in.AssetOut))
	}
	{
		const prefix string = ",\"recipient\":"
		out.RawString(prefix)
		out.String(string(in.Recipient))
	}
	if in.MinAmountOut != nil {
		const prefix string = ",\"min_amount_out\":"
		out.RawString(prefix)
		out.String(string(*in.MinAmountOut))
	}
	if in.Beneficiary != nil {
		const prefix string = ",\"beneficiary\":"
		out.RawString(prefix)
		out.String(string(*in.Beneficiary))
	}
	if in.RefBps != nil {
		const prefix string = ",\"ref_bps\":"
		out.RawString(prefix)
		out.Uint64(uint64(*in.RefBps))
	}
	if in.ReturnAddress != nil {
		const prefix string = ",\"return_address\":"
		out.RawString(prefix)
		tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp11(out, *in.ReturnAddress)
	}
	if len(in.Metadata) != 0 {
		const prefix string = ",\"metadata\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v8First := true
			for v8Name, v8Value := range in.Metadata {
				if v8First {
					v8First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v8Name))
				out.RawByte(':')
				out.String(string(v8Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"amount_in\":"
		out.RawString(prefix)
		out.String(string(in.AmountIn))
	}
	if in.DestinationChain != "" {
		const prefix string = ",\"destination_chain\":"
		out.RawString(prefix)
		out.String(string(in.DestinationChain))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v DexInstruction) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp10(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *DexInstruction) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp10(l, v)
}
func tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp11(in *jlexer.Lexer, out *ReturnAddress) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "chain":
			out.Chain = string(in.String())
		case "address":
			out.Address = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp11(out *jwriter.Writer, in ReturnAddress) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"chain\":"
		out.RawString(prefix[1:])
		out.String(string(in.Chain))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	out.RawByte('}')
}
func tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp12(in *jlexer.Lexer, out *ConfirmSpendParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "tx_data":
			if in.IsNull() {
				in.Skip()
				out.TxData = nil
			} else {
				if out.TxData == nil {
					out.TxData = new(VerificationRequest)
				}
				(*out.TxData).UnmarshalTinyJSON(in)
			}
		case "indices":
			if in.IsNull() {
				in.Skip()
				out.Indices = nil
			} else {
				in.Delim('[')
				if out.Indices == nil {
					if !in.IsDelim(']') {
						out.Indices = make([]uint32, 0, 16)
					} else {
						out.Indices = []uint32{}
					}
				} else {
					out.Indices = (out.Indices)[:0]
				}
				for !in.IsDelim(']') {
					var v9 uint32
					v9 = uint32(in.Uint32())
					out.Indices = append(out.Indices, v9)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp12(out *jwriter.Writer, in ConfirmSpendParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"tx_data\":"
		out.RawString(prefix[1:])
		if in.TxData == nil {
			out.RawString("null")
		} else {
			(*in.TxData).MarshalTinyJSON(out)
		}
	}
	{
		const prefix string = ",\"indices\":"
		out.RawString(prefix)
		if in.Indices == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v10, v11 := range in.Indices {
				if v10 > 0 {
					out.RawByte(',')
				}
				out.Uint32(uint32(v11))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v ConfirmSpendParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp12(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *ConfirmSpendParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp12(l, v)
}
func tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp13(in *jlexer.Lexer, out *AllowanceParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "spender":
			out.Spender = string(in.String())
		case "amount":
			out.Amount = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp13(out *jwriter.Writer, in AllowanceParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"spender\":"
		out.RawString(prefix[1:])
		out.String(string(in.Spender))
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.String(string(in.Amount))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v AllowanceParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp13(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *AllowanceParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp13(l, v)
}
func tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp14(in *jlexer.Lexer, out *AggregatedSig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "agg_sig_hex":
			out.AggSigHex = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp14(out *jwriter.Writer, in AggregatedSig) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"agg_sig_hex\":"
		out.RawString(prefix[1:])
		out.String(string(in.AggSigHex))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v AggregatedSig) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp14(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *AggregatedSig) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp14(l, v)
}
func tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp15(in *jlexer.Lexer, out *AccountInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "modified_at":
			out.ModifiedAt = uint64(in.Uint64())
		case "address":
			out.Address = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp15(out *jwriter.Writer, in AccountInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"modified_at\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.ModifiedAt))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v AccountInfo) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA043f2bcEncodeDashMappingContractContractMappingTinyjsonTmp15(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *AccountInfo) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA043f2bcDecodeDashMappingContractContractMappingTinyjsonTmp15(l, v)
}
